# Generated by Django 5.0.6 on 2024-07-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Цена'),
        ),
    ]
