# Generated by Django 5.0.6 on 2024-06-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона ')),
                ('our_location', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта ')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': ' Контакты',
            },
        ),
    ]
