# Generated by Django 5.0.6 on 2024-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='info_users/', verbose_name='Задний Фон')),
                ('image', models.ImageField(upload_to='info_users', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'страница для Бронирование ',
                'verbose_name_plural': 'страница для Бронирование',
            },
        ),
    ]
