# Generated by Django 5.0.6 on 2024-06-28 09:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content2',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание новости 2'),
        ),
        migrations.AddField(
            model_name='news',
            name='content3',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание новости 3'),
        ),
    ]
