# Generated by Django 5.0.6 on 2024-06-28 09:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_news_content2_news_content3'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content4',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание новости 4'),
        ),
    ]
