# Generated by Django 5.0.6 on 2024-06-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Главная страница')),
                ('the_background', models.ImageField(upload_to='info_users', verbose_name='Задний Фон')),
                ('image', models.ImageField(upload_to='info_users/', verbose_name='Фотография  загловка')),
                ('discription', models.TextField(max_length=255, verbose_name='описания заговка')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': ' Главная страницы',
            },
        ),
    ]
