# Generated by Django 5.0.6 on 2024-06-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_home_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='the_background',
            new_name='image',
        ),
    ]
