# Generated by Django 5.0.6 on 2024-06-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_about_rename_discription_home_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тайтла')),
                ('text', models.TextField(max_length=255, verbose_name='Текст')),
                ('fullname', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('photo', models.ImageField(upload_to='photo_employee/', verbose_name='Фотография')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
                ('facebook', models.URLField(max_length=255, verbose_name='Facebook')),
                ('twitter', models.URLField(max_length=255, verbose_name='Twitter')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('instagram', models.URLField(max_length=255, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
