# Generated by Django 5.0.6 on 2024-06-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='text',
        ),
        migrations.RemoveField(
            model_name='team',
            name='title',
        ),
    ]
