# Generated by Django 5.0.6 on 2024-06-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание о себе'),
            preserve_default=False,
        ),
    ]
