# Generated by Django 5.0.6 on 2024-06-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='age',
            field=models.PositiveIntegerField(default=1, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
