# Generated by Django 5.0.6 on 2024-06-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_team_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='phone',
            field=models.PositiveIntegerField(default=1, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
