# Generated by Django 5.0.6 on 2024-06-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_team_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Нужно вставить картины своих работ', upload_to='my_works/', verbose_name='Мои работы')),
            ],
            options={
                'verbose_name': 'Мои работы',
                'verbose_name_plural': 'Мои работы',
            },
        ),
    ]
