# Generated by Django 5.0.6 on 2024-06-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_teamworks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamworks',
            options={'verbose_name': 'Работа повара', 'verbose_name_plural': 'Работы поваров'},
        ),
        migrations.AlterField(
            model_name='teamworks',
            name='image',
            field=models.ImageField(help_text='Нужно вставить фотографии работ повара', upload_to='my_works/', verbose_name='Мои работы'),
        ),
    ]
